---
# Exercise
---

## 2D Arithmetic

Remember how you calculated the Body Mass Index for all baseball players? `numpy` was able to perform all calculations element-wise (i.e. element by element). For 2D `numpy` arrays this isn't any different! You can combine matrices with single numbers, with vectors, and with other matrices.

Execute the code below in the IPython shell and see if you understand:

``` python
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat + np_mat
```

`np_baseball` is coded for you; it's again a 2D `numpy` array with 3 columns representing height (in inches), weight (in pounds) and age (in years).

In [2]:
# IPython Shell
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [3]:
np_mat + np.array([10, 10])

array([[11, 12],
       [13, 14],
       [15, 16]])

In [4]:
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

---
### Instructions `100xp`
---

* You managed to get hold of the changes in height, weight and age of all baseball players. It is available as a 2D `numpy` array, `updated`. Add `np_baseball` and `updated` and print out the result.
* You want to convert the units of height and weight to metric (meters and kilograms respectively). As a first step, create a `numpy` array with three values: `0.0254`, `0.453592` and `1`. Name this array `conversion`.
* Multiply `np_baseball` with `conversion` and print out the result.

---

In [11]:
# script.py

# baseball is available as a regular list of lists
# CM:: refactor with pandas and local csv file
import pandas
colnames = ["Name", "Team", "Position", "Height", "Weight", "Age", "PosCategory"]
data = pandas.read_csv("00_1_baseball_players.csv", names=colnames)
baseball = [data.Height.tolist(), data.Weight.tolist(), data.Age.tolist()]
# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)
# CM:: transpose axes
np_baseball = np_baseball.transpose()

# Print out addition of np_baseball and updated
# CM:: missing updated use np_baseball instead
print(np_baseball + np_baseball)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[148.   360.    45.98]
 [148.   430.    69.38]
 [144.   420.    61.56]
 ...
 [150.   410.    50.38]
 [150.   380.    62.02]
 [146.   390.    55.84]]
[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]
