---
# Exercise
---

## Explore the baseball data

Because the mean and median are so far apart, you decide to complain to the MLB. They find the error and send the corrected data over to you. It's again available as a 2D Numpy array `np_baseball`, with three columns.

The Python script on the right already includes code to print out informative messages with the different summary statistics. Can you finish the job?

---
### Instructions `100xp`
---

* The code to print out the mean height is already included. Complete the code for the median height. Replace `None` with the correct code.
* Use [<u>`np.std()`</u>](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.std.html) on the first column of `np_baseball` to calculate `stddev`. Replace `None` with the correct code.
* Do big players tend to be heavier? Use `np.corrcoef()` to store the correlation between the first and second column of `np_baseball` in `corr`. Replace `None` with the correct code.

---

In [5]:
# script.py

# baseball is available as a regular list of lists
# CM:: refactor with pandas and local csv file
import pandas
colnames = ["Name", "Team", "Position", "Height", "Weight", "Age", "PosCategory"]
data = pandas.read_csv("00_1_baseball_players.csv", names=colnames)
baseball = [data.Height.tolist(), data.Weight.tolist(), data.Age.tolist()]

# Import numpy
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)
# CM:: transpose axes
np_baseball = np_baseball.transpose()

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:, 0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:, 0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:, 0:2])
print("Correlation: " + str(corr))

Average: 73.6896551724138
Median: 74.0
Standard Deviation: 2.312791881046546
Correlation: [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
